apiVersion: v1
kind: Namespace
metadata:
  name: hello-world-prod
  labels:
    environment-id: env_cbd4c5c6-8e7c-49bd-a008-cf6a001cb03a
    project-id: project_b4ada7e7-9970-48a7-aaeb-4a0e08556f53
    project-name: Hello World
    environment-name: prod
    organization-id: org_219aede3-da6b-4fe5-8560-fc32e8fb3a28
